name: CI
on:
  push:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 18.14.0
          cache: pnpm
      - run: pnpm install
      - run: pnpm typecheck
      - run: pnpm test
      - run: pnpm build
